language: node_js

node_js:
  - "8"

env:
  matrix:
    - TEST_TYPE=lint
    - TEST_TYPE=build
    - TEST_TYPE=test-all
#    - TEST_TYPE=test-dist

addons:
  apt:
    packages:
      - xvfb

sudo: required

services:
  - docker

cache:
  directories:
    - "node_modules"

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

script:
  - |
    if [ "$TEST_TYPE" = lint ]; then
      npm run lint
    elif [ "$TEST_TYPE" = build && "$TRAVIS_BRANCH" == "production" ]; then
      npm run build
    elif [ "$TEST_TYPE" = test-all ]; then
      npm run test:all
#    elif [ "$TEST_TYPE" = test-dist ]; then
#      npm run site
#      mv dist/* ./
#      php -S localhost:8000 &
#      DEBUG=* npm test .e2e.js
    fi

after_success:
  - if [ "$TRAVIS_BRANCH" == "production" && "$TEST_TYPE" == build ]; then
    docker build -t registry.cn-beijing.aliyuncs.com/a-cubic/cbec-b2b-web .
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.cn-beijing.aliyuncs.com;
    docker push registry.cn-beijing.aliyuncs.com/a-cubic/cbec-b2b-web;
    fi
